config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "pages#landing"
  get '/profile/user/:id', to: 'users#profile', as: 'user_profile'

  resources :inquiries
  resources :rooms do 
    collection do
      get "manage" 
    end
  end

  resources :amenities
  
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user

  validates :first_name, :email, :words, presence: true

  def phone_exists
    self.phone.nil? ? "not available" : self.phone
  end

  def user_name
    return self.first_name + " " + self.last_name
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_inquiry, only: [:destroy]
  
  def index
    @user = current_user
    @inquiries = @user.admin? ? Inquiry.all : @user.inquiries
  end

  def new
    @inquiry = Inquiry.new
  end

  def create
    @user = current_user
    @inquiry = @user.inquiries.build(inquiry_params)
    if @inquiry.save
        redirect_back fallback_location: root_path, notice: "Your Inquiry was submit successfully"
    else
      redirect_back fallback_location: root_path, alert: @inquiry.errors.full_messages.to_sentence
        # render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @inquiry.destroy
      redirect_to inquiries_path, notice: "Inquiry removed successfully"
    else
      redirect_to inquiries_path, alert: @inquiry.errors.full_messages.to_sentence
    end
  end

  def find_inquiry
    @inquiry = Inquiry.find(params[:id])
  end

  def inquiry_params
    params.require(:inquiry).permit(:first_name, :last_name, :email, :phone, :words)
  end
end

app/views/inquiries/index.html.erb
<div class="row">
  <%= render partial: "/layouts/side_bar"%>

  <div class="col-lg-10 col-md-9 col-xs-12 justify-content-center">
    <div class="text-center">
      <% if current_user.admin? %>
        <h2 class="text-center p-5">Inquiries Received</h2>
      <% else %>
        <h2 class="text-center p-5">History of Submissions</h2>
      <% end %>
      <table class="table">
        <thead>
          <% if @inquiries.exists? == false || @inquiries.empty? %>
            No Inquiries made yet <span><%= link_to "Create new", new_inquiry_path(), class: " mx-2"%></span>
          <% else %> 
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Phone #</th>
              <th scope="col">Email</th>
              <th scope="col">Message</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @inquiries.each do |inquiry|%>
              <tr>
                <th scope="row"><%= inquiry.id %></th>
                <td><%= inquiry.user_name.capitalize %></td>
                <td><%= inquiry.phone_exists %></td>
                <td><%= inquiry.email.capitalize %></td>
                <td><%= inquiry.words.truncate(40) %></td>
                <td><%= button_to 'Remove', inquiry_path(inquiry.id), method: :delete, data: {confirm: "Are You Sure you want to delete this inquiry?"}, class: "btn btn-outline-custom"%></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>    
  </div>
</div>

app/views/inquiries/new.html.erb
<style>
:root {
  /*--primary-color: #ff385c;*/
  --primary-color: #ff385c;
  --primary-hover: #e61e4d;
  --text-color: #333;
  --light-gray: #f7f7f7;
  --medium-gray: #ddd;
  --dark-gray: #666;
}

body {
  font-family: "Raleway", sans-serif;
  font-optical-sizing: auto;
  font-style: normal;
  color: var(--text-color);
  background-color: var(--light-gray);
}

.navbar-brand {
  font-weight: 700;
  color: #000000;
  font-size: 24px;
}

.txt-color {
color: #DDDDDD;
}


.nav-link {
  font-weight: 500;
}

.nav-link:hover {
  color: red;
}

.btn-primary-custom {
  background-color: var(--primary-color);
  border-color: var(--primary-color);
  color: white;
}

.btn-primary-custom:hover {
  background-color: var(--primary-hover);
  border-color: var(--primary-hover);
}

.btn-outline-custom {
  border-color: var(--medium-gray);
}

<%# .btn-outline-custom:hover {
  background-color: var(--light-gray);
  border: 1px solid #DDDDDD;
} %>

/* Hero Section */
.hero {
  margin-top: 20px;
}

/* Carousel Styles */
.carousel {
  position: relative;
  width: 100%;
  height: 500px;
  overflow: hidden;
  border-radius: 12px;
}

.carousel-inner {
  display: flex;
  transition: transform 0.5s ease;
  height: 100%;
}

.carousel-item {
  min-width: 100%;
  height: 100%;
}

.carousel-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.carousel-control {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  background-color: rgba(255, 255, 255, 0.7);
  border: none;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  z-index: 10;
}

.carousel-control.prev {
  left: 20px;
}

.carousel-control.next {
  right: 20px;
}

.carousel-indicators {
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  gap: 10px;
}

.indicator {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background-color: rgba(255, 255, 255, 0.5);
  cursor: pointer;
}

.indicator.active {
  background-color: white;
}

.property-title {
  font-size: 28px;
  margin-bottom: 10px;
}

.property-location {

}

.highlight-icon {
  color: black;
  margin-right: 5px;
}

.amenity-icon {
  color: black;
  margin-right: 8px;
  width: 20px;
  text-align: center;
}

.booking-card {
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 80px;
}

.price {
  font-size: 22px;
  font-weight: 600;
}

.price-period {
  font-weight: normal;
  font-size: 16px;
}

.review-card {
  border-radius: 12px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
  padding: 20px;
  margin-bottom: 20px;
}

.reviewer-avatar {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  object-fit: cover;
}

.review-date {
  color: var(--dark-gray);
  font-size: 14px;
}

/*.rating-stars {
  color: var(--primary-color);
}*/

.average-rating {
  font-size: 48px;
  font-weight: 600;
}

footer {
  background-color: white;
  padding: 40px 0 20px;
  margin-top: 50px;
}

.footer-link {
  text-decoration: none;
}

.footer-link:hover {
  color: var(--primary-color);
}

.footer-bottom {
  border-top: 1px solid var(--medium-gray);
  padding-top: 20px;
  margin-top: 30px;
}

.social-icon {
  color: var(--text-color);
  font-size: 18px;
  margin-left: 15px;
}

.admin-actions {
  margin-top: 20px;
}

.btn-admin {
  background-color: var(--text-color);
  color: white;
  border: none;
}

.btn-admin:hover {
  background-color: #555;
  color: white;
}

.modal-dialog {
  margin-top: 8rem;
}

@media (max-width: 768px) {
  .property-title {
      font-size: 24px;
  }
  
  .average-rating {
      font-size: 36px;
  }
}






/*contact us*/
* {
  margin: 0px;
  padding: 0px;
  box-sizing: border-box;
}

body,
html {
  height: 100%;
  /* font-family: Montserrat-Regular, sans-serif; */
}

a {
  /* font-family: Montserrat-Regular; */
  font-size: 14px;
  line-height: 1.7;
  color: #666666;
  margin: 0px;
  transition: all 0.4s;
  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
}

/* a:focus {
  outline: none !important;
}

a:hover {
  text-decoration: none;
  color: #57b846;
} */

h1,
h2,
h3,
h4,
h5,
h6 {
  margin: 0px;
}

p {
  /* font-family: Montserrat-Regular; */
  font-size: 14px;
  line-height: 1.7;
  color: #666666;
  margin: 0px;
}

ul,
li {
  margin: 0px;
  list-style-type: none;
}

input {
  outline: none;
  border: none;
}

textarea {
  outline: none;
  border: none;
}

textarea:focus,
input:focus {
  border-color: transparent !important;
}

input:focus::-webkit-input-placeholder {
  color: transparent;
}

input:focus:-moz-placeholder {
  color: transparent;
}

input:focus::-moz-placeholder {
  color: transparent;
}

input:focus:-ms-input-placeholder {
  color: transparent;
}

textarea:focus::-webkit-input-placeholder {
  color: transparent;
}

textarea:focus:-moz-placeholder {
  color: transparent;
}

textarea:focus::-moz-placeholder {
  color: transparent;
}

textarea:focus:-ms-input-placeholder {
  color: transparent;
}

input::-webkit-input-placeholder {
  color: #aaaaaa;
}

input:-moz-placeholder {
  color: #aaaaaa;
}

input::-moz-placeholder {
  color: #aaaaaa;
}

input:-ms-input-placeholder {
  color: #aaaaaa;
}

textarea::-webkit-input-placeholder {
  color: #aaaaaa;
}

textarea:-moz-placeholder {
  color: #aaaaaa;
}

textarea::-moz-placeholder {
  color: #aaaaaa;
}

textarea:-ms-input-placeholder {
  color: #aaaaaa;
}

/*---------------------------------------------*/
button {
  outline: none !important;
  border: none;
  background: transparent;
}

button:hover {
  cursor: pointer;
}

iframe {
  border: none !important;
}



.bg-contact100 {
  width: 100%;
  background-repeat: no-repeat;
  background-position: center center;
  background-size: cover;
}

.container-contact100 {
  width: 100%;
  min-height: 100vh;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  padding: 15px;
  background: white; 
  box-shadow: 5px 10px #888888;
  /*background: rgba(132, 106, 221, 0.9);*/
}

.wrap-contact100 {
  width: 1163px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;

  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  padding: 110px 130px 157px 148px;
  box-shadow: -5px 0px 35px -17.0px #888888;
}

/*------------------------------------------------------------------
[  ]*/
.contact100-pic {
  width: 310px;
  padding-top: 55px;
}

.contact100-pic img {
  max-width: 100%;
}


.contact100-form {
  width: 390px;
}

.contact100-form-title {
  display: block;
  /* font-family: Montserrat-ExtraBold; */
  font-size: 24px;
  color: #333333;
  line-height: 1.2;
  text-align: left;
  padding-bottom: 36px;
}

input.input100 {
  height: 50px;
  border-radius: 25px;
  padding: 0 30px 0 50px;
}

input.input100[name="email"] {
  padding: 0 30px 0 54px;
}

textarea.input100 {
  min-height: 150px;
  border-radius: 25px;
  padding: 14px 30px;
}

.wrap-input100 {
  position: relative;
  width: 100%;
  z-index: 1;
  margin-bottom: 10px;
}

.input100 {
  display: block;
  width: 100%;
  background: #e6e6e6;
  /* font-family: Montserrat-Bold; */
  font-size: 15px;
  line-height: 1.5;
  color: #666666;
}


.focus-input100 {
  display: block;
  position: absolute;
  border-radius: 25px;
  bottom: 0;
  left: 0;
  z-index: -1;
  width: 100%;
  height: 100%;
  box-shadow: 0px 0px 0px 0px;
  color: rgba(132, 106, 221, 0.5);
}

.input100:focus+.focus-input100 {
  -webkit-animation: anim-shadow 0.5s ease-in-out forwards;
  animation: anim-shadow 0.5s ease-in-out forwards;
}

@-webkit-keyframes anim-shadow {
  to {
      box-shadow: 0px 0px 60px 25px;
      opacity: 0;
  }
}

@keyframes anim-shadow {
  to {
      box-shadow: 0px 0px 60px 25px;
      opacity: 0;
  }
}

.symbol-input100 {
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  align-items: center;
  position: absolute;
  border-radius: 25px;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  padding-left: 30px;
  pointer-events: none;
  color: #aaaaaa;
  font-size: 15px;

  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
  transition: all 0.4s;
}

.input100:focus+.focus-input100+.symbol-input100 {
  color: #846add;
  padding-left: 22px;
}

.container-contact100-form-btn {
  width: 100%;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  padding-top: 20px;
}

.contact100-form-btn {
  width: 100%;
  height: 50px;
  border-radius: 25px;
  background: #846add;
  /* font-family: Montserrat-Bold; */
  font-size: 15px;
  line-height: 1.5;
  color: #fff;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 0 25px;

  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
  transition: all 0.4s;
}

.contact100-form-btn:hover {
  background: #333333;
}


@media (max-width: 1200px) {
  .contact100-pic {
      width: 33.5%;
  }

  .contact100-form {
      width: 44%;
  }
}

@media (max-width: 992px) {
  .wrap-contact100 {
      padding: 110px 80px 157px 90px;
  }

  .contact100-pic {
      width: 35%;
  }

  .contact100-form {
      width: 55%;
  }
}

@media (max-width: 768px) {
  .wrap-contact100 {
      padding: 110px 80px 157px 80px;
  }

  .contact100-pic {
      display: none;
  }

  .contact100-form {
      width: 100%;
  }
}

@media (max-width: 576px) {
  .wrap-contact100 {
      padding: 110px 15px 157px 15px;
  }
}



.validate-input {
  position: relative;
}

.alert-validate::before {
  content: attr(data-validate);
  position: absolute;
  max-width: 70%;
  background-color: white;
  border: 1px solid #c80000;
  border-radius: 13px;
  padding: 4px 25px 4px 10px;
  top: 50%;
  -webkit-transform: translateY(-50%);
  -moz-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  -o-transform: translateY(-50%);
  transform: translateY(-50%);
  right: 8px;
  pointer-events: none;

  /* font-family: Montserrat-Medium; */
  color: #c80000;
  font-size: 13px;
  line-height: 1.4;
  text-align: left;

  visibility: hidden;
  opacity: 0;

  -webkit-transition: opacity 0.4s;
  -o-transition: opacity 0.4s;
  -moz-transition: opacity 0.4s;
  transition: opacity 0.4s;
}

.alert-validate::after {
  content: "\f06a";
  /* font-family: FontAwesome; */
  display: block;
  position: absolute;
  color: #c80000;
  font-size: 15px;
  top: 50%;
  -webkit-transform: translateY(-50%);
  -moz-transform: translateY(-50%);
  -ms-transform: translateY(-50%);
  -o-transform: translateY(-50%);
  transform: translateY(-50%);
  right: 13px;
}

.alert-validate:hover:before {
  visibility: visible;
  opacity: 1;
}

@media (max-width: 992px) {
  .alert-validate::before {
      visibility: visible;
      opacity: 1;
  }
}

</style>

<div class="bg-contact100">
    <div class="container-contact100">
        <div class="wrap-contact100">
            <div class="contact100-pic js-tilt" data-tilt>
                <img src="https://i.imgur.com/VRFiMzM.png" alt="IMG">
            </div>
            <%= form_with(model: @inquiry, local: true, html: {class: "contact100-form validate-form" })  do |f| %>
              <span class="contact100-form-title">
                  Send Us an Inquiry
              </span>
              <div class="wrap-input100 validate-input" data-validate="First Name is required">
                  <%= f.text_field :first_name, class:"input100", placeholder: "First Name" %>
                  <span class="focus-input100"></span>
                  <span class="symbol-input100">
                      <i class="fa fa-user" aria-hidden="true"></i>
                  </span>
              </div>
              <div class="wrap-input100 validate-input">
                <%= f.text_field :last_name, class:"input100", placeholder: "Last Name" %>
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <i class="fa fa-user" aria-hidden="true"></i>
                </span>
              </div>
              <div class="wrap-input100 validate-input">
                <%= f.text_field :phone, class:"input100", placeholder: "Phone Number" %>
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                </span>
              </div>
              <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                <%= f.text_field :email, class:"input100", placeholder: "Email" %>
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <i class="fa fa-email" aria-hidden="true"></i>
                </span>
              </div>
              <div class="wrap-input100 validate-input" data-validate="Message is required">
                <%= f.text_area :words, class:"input100", placeholder:"Message" %>
                <span class="focus-input100"></span>
                <span class="symbol-input100">
                    <span class="focus-input100"></span>
                </span>
              </div>
              <div class="container-contact100-form-btn">
                <%= f.submit :Send, class:"contact100-form-btn"%>
              </div>
            <% end %>
        </div>
    </div>
</div>