config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "pages#landing"
  get '/profile/user/:id', to: 'users#profile', as: 'user_profile'

  resources :inquiries
  resources :rooms do 
    collection do
      get "manage" 
    end
  end

  resources :amenities
  
end

app/views/layouts/_carousel.html.erb
<div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel" data-bs-interval="2000">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="5" aria-label="Slide 6"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://i.imgur.com/bmlXwjk.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/gCq8OQz.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/j5uKpRq.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/G1trSin.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/FMjAVbW.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/XPos8yZ.jpeg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5></h5>
        <p></p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
<div class="container">
  <div class="row py-3">
    <div class="col-md-3 col-6 mb-4">
      <h5>Support</h5>
      <ul class="list-unstyled">
        <li class="mb-2"><a href="#" class="footer-link">Help Center</a></li>
        <li class="mb-2"><a href="#" class="footer-link">Safety information</a></li>
        <li class="mb-2"><a href="#" class="footer-link">Cancellation options</a></li>
        <li><a href="#" class="footer-link">Our COVID-19 Response</a></li>
      </ul>
    </div>
    <div class="col-md-3 col-6 mb-4">
      <h5>Community</h5>
      <ul class="list-unstyled">
        <li class="mb-2"><a href="#" class="footer-link">Disaster relief housing</a></li>
        <li class="mb-2"><a href="#" class="footer-link">Support refugees</a></li>
        <li><a href="#" class="footer-link">Combating discrimination</a></li>
      </ul>
    </div>
    <div class="col-md-3 col-6 mb-4">
      <h5>Hosting</h5>
      <ul class="list-unstyled">
        <li class="mb-2"><a href="#" class="footer-link">Try hosting</a></li>
        <li class="mb-2"><a href="#" class="footer-link">AirCover for Hosts</a></li>
        <li class="mb-2"><a href="#" class="footer-link">Explore hosting resources</a></li>
        <li><a href="#" class="footer-link">Visit our community forum</a></li>
      </ul>
    </div>
    <div class="col-md-3 col-6 mb-4">
      <h5>About</h5>
      <ul class="list-unstyled">
        <li class="mb-2"><a href="#" class="footer-link">Newsroom</a></li>
        <li class="mb-2"><a href="#" class="footer-link">Learn about new features</a></li>
        <li class="mb-2"><a href="#" class="footer-link">Careers</a></li>
        <li><a href="#" class="footer-link">Investors</a></li>
      </ul>
    </div>
  </div>
  
  <div class="footer-bottom d-flex flex-column flex-md-row justify-content-between align-items-center">
    <div class="mb-3 mb-md-0 text-muted">© 2025 Venue 360, Inc. All rights reserved</div>
    <div>
      <a href="tel:+23290423234" class="social-icon"><i class="fa-solid fa-phone"></i>
      <a href="#" class="social-icon"><i class="fab fa-facebook-f"></i></a>
      <a href="#" class="social-icon"><i class="fab fa-twitter"></i></a>
      <a href="#" class="social-icon"><i class="fab fa-instagram"></i></a>
    </div>
  </div>
</div>
</footer>

app/views/layouts/_gallary.html.erb
<div class="col-lg-6 p-0">
	<div class="row mx-3 mb-2">
		<div class="col-lg-6 col-md-12 col-xs-12 p-0" id="gc-1">
				<div class="img-container" style="height: 230px;">
						<img src="https://i.postimg.cc/k4BQN0hs/IMG-20250427-WA0071.jpg" alt="Gallery image 1" class="gallery-img">
				</div>
		</div>
		<div class="col-lg-6 col-md-12 col-xs-12 p-0" id="gc-2">
				<div class="img-container last-ones" style="height: 230px;">
						<img src="https://i.postimg.cc/xTrvHFGG/IMG-20250427-WA0078.jpg" alt="Gallery image 2" class="gallery-img">
				</div>
		</div>
	</div>

	<div class="row mx-3">
		<div class="col-lg-6 col-md-12 col-xs-12 p-0" id="gc-3">
				<div class="img-container" style="height: 230px;">
						<img src="https://i.postimg.cc/cCtv6Z5q/IMG-20250427-WA0066.jpg" alt="Gallery image 3" class="gallery-img">
				</div>
		</div>
		<div class="col-lg-6 col-md-12 col-xs-12 p-0" id="gc-4">
				<div class="img-container last-ones" style="height: 230px;">
						<img src="https://i.postimg.cc/7ZnnqM23/IMG-20250427-WA0067.jpg" alt="Gallery image 4" class="gallery-img">
				</div>
		</div>
	</div>
</div>

<!-- IMAGE VIEWER MODAL -->
	<div id="image-viewer">
		<span class="close">&times;</span>
		<img class="modal-content" id="full-image">
	</div>
<script>
	// JS FOR IMAGE VIEWING
	$(".img-container img").click(function(){
			$("#full-image").attr("src", $(this).attr("src"));
			$('#image-viewer').show();
	});
	
	$("#image-viewer .close").click(function(){
			$('#image-viewer').hide();
	});

	$("#image-viewer").click(function(){
			$('#image-viewer').hide();
	});
</script>

app/views/layouts/_gmaps.html.erb
<div class="container my-5">
  <h4><strong>Where you’ll be</strong></h4>
  <div class="my-3">
    <p class="text-muted">
      <i class="fas fa-map-marker-alt text-black"></i>
      <strong>63 Sir Samuel Lewis Road. Aberdeen, Freetown, Sierra Leone</strong>
    </p>
  </div>

  <div class="row align-items-center my-4">
    <!-- Map Column -->
    <div class="col-lg-12 mb-4 mb-lg-0">
      <div class="map-container">
        <!-- Replace with your actual location coordinates -->
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3946.064141554188!2d-13.277012399999998!3d8.4931448!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xf04c502e3237915%3A0xc4af2d8fe65473ec!2sVenue%20360%20sl!5e0!3m2!1sen!2ssl!4v1746483410031!5m2!1sen!2ssl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
        </iframe>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Header/Navbar -->
<%# byebug %>
<nav class="navbar navbar-expand-lg navbar-light bg-white sticky-top shadow-sm">
  <div class="container">
    <%= link_to 'Venue 360', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <div class="dropdown d-flex">
            <%= link_to "Rooms", rooms_path, class: "nav-link" %>
            <button class="dropdown-toggle nav-link" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              More
            </button>
            <ul class="dropdown-menu">
              <% Room.all.each do |room| %>
                <li>
                  <%= link_to room.name, room, class: "dropdown-item" %>
                </li>
              <% end %>
            </ul>
          </div>
        </li>
        <span class="py-2 nav-span">|</span>
        <li class="nav-item">
          <a class="nav-link" href="#">Any Week</a>
        </li>
        <span class="py-2 nav-span">|</span>
        <li class="nav-item">
          <a class="nav-link" href="#">Add Guests</a>
        </li>
      </ul>
      <div class="d-flex ml-a">
        <% if current_user %>
        <%# if !request.path_info.include?('profile') %>
          <%= link_to "Profile", user_profile_path(current_user.id), class: "btn btn-outline-custom mx-1"%>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-custom" %>
        <% else %>
          <button class="btn btn-outline-custom me-2" id="openLoginModal">Log in</button>
          <button class="btn btn-outline-custom" id="openSignupModal">Sign up</button>
        <% end %>
        <%= link_to "Contact Us", new_inquiry_path(), class: "btn btn-outline-custom mx-1"%>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_side_bar.html.erb
<nav class="col-lg-2 col-md-3 col-xs-12 sidebar d-flex flex-column ">
  <div class="profile-section pt-3 px-4">
      <div class="d-flex align-items-center">
        <div class="p-2">
          <h4 class="logo-text fw-bold mb-0">
            <% if current_user.admin?%>
              Admin 
            <% else %>
              User 
            <% end %>   
          </h4>
          <p class="text-white small hide-on-collapse">Dashboard</p>
        </div>
    </div>
    </div>
  <!--div class="profile-section mt-auto p-4"-->

  <div class="nav flex-column">
    <% if current_user %>
        <%= link_to user_profile_path(current_user.id), class: "sidebar-link active text-decoration-none p-3" do %>
          <i class="fas fa-home me-3"></i>
          <span class="hide-on-collapse">Dashboard</span>
        <% end %>
      <a href="#" class="">
        <%= link_to inquiries_path, class: "sidebar-link text-decoration-none p-3" do %>
          <i class="fas fa-commenting me-3"></i>
          <span class="hide-on-collapse">Inquiries</span>
        <% end %>
      <%= link_to new_inquiry_path, class: "sidebar-link text-decoration-none p-3" do %>
        <i class="fas fa-calendar-check me-3"></i>
        <span class="hide-on-collapse">Reservations</span>
      <% end %>
      <% if current_user.admin?%>
        <a href="#" class="sidebar-link text-decoration-none p-3">
          <i class="fas fa-users me-3"></i>
          <span class="hide-on-collapse">Users</span>
        </a>
        <a href="#" class="sidebar-link text-decoration-none p-3">
          <i class="fas fa-gear me-3"></i>
          <span class="hide-on-collapse">Settings</span>
        </a>
        <div class="rooms">
          <div class="sidebar-link p-3">  
            <i class="fas fa-users me-3"></i>
            <button class="dropdown-toggle sidebar-collapsible-button" data-bs-toggle="collapse" data-bs-target="#rooms-collapse" aria-expanded="false">
              Rooms
            </button>
          </div>
          <div class="collapse" id="rooms-collapse" style="">
            <ul class="px-3">
              <li><%= link_to "Add New Listing", new_room_path(current_user.id), class: "sidebar-link-drop-item" %></li>
              <li><%= link_to "Manage", manage_rooms_path, class: "sidebar-link-drop-item" %></li>
            </ul>
          </div>
        </div>
        <div class="amenities">
          <div class="sidebar-link p-3">
            <i class="fas fa-users me-3"></i>
            <button class="dropdown-toggle sidebar-collapsible-button" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
              Amenities
            </button>
          </div>
          <div class="collapse" id="account-collapse" style="">
            <ul class="px-3">
              <li><%= link_to "Create Amenity", new_amenity_path(), class: "sidebar-link-drop-item" %></li>
              <li><%= link_to "Manage", amenities_path, class: "sidebar-link-drop-item" %></li>
            </ul>
          </div>
        </div>
      <% else %>
      <% end %>
    <% end %>  
  </div>  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <title><%= content_for(:title) || "Venue 360" %></title>-->
    <title>Venue 360 - Premium Hotel Booking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "landing", "data-turbo-track": "reload" %>

    <%# Includee javascripts files %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'main', 'data-turbolinks-track': 'reload' %>    
    <%#= javascript_include_tag "main", "data-turbolinks-track": true  %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/navigation" %>
    <%= render 'layouts/messages'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>